CREATE TABLE list (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    summary TEXT,
    address TEXT NOT NULL,
    contact TEXT NOT NULL,
    type TEXT NOT NULL,
    zip TEXT NOT NULL,
    username INTEGER REFERENCES users(id),
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    date_modified TIMESTAMP DEFAULT now()
);
